[package]
name = "seating-arrangement"
version = "0.1.0"
authors = ["James Wilson <me@unbui.lt>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1.1"
structopt = "0.2"
itertools = "0.8"
rand = "0.7"